export const x_path = 'https://twitter.com'
export const telegram_path = 'https://t.me/username'
export const dexscreener_path = 'https://dexscreener.com/'
export const raydium_path = 'https://raydium.io/swap/'
export const totalSupply = '1000000000'